Django/todo/items/urls.py
from django.urls import path
from . import views

app_name = 'items'

urlpatterns = [
    path('taskedit/<int:pk>/', views.TaskEdit.as_view(), name='taskedit'),
    path('taskdetail/<int:pk>/', views.TaskDetail.as_view(), name='taskdetail'),
    path('taskcreate/', views.CreateTask.as_view(), name='taskcreate'),
]

Django/todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('home/', include('items.urls')),
]

Django/todo/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('signin/', views.SignInView.as_view(), name='signin'),
    path('home/', views.Home.as_view(), name='home'),
    path('logout/', views.logoutView, name='logout'),
]

Django/todo/items/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Tasks(models.Model):
    title = models.CharField(max_length=150)
    description = models.TextField()
    last_modified = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Tasks"

    def __str__(self):
        return self.title

Django/todo/users/models.py
from django.db import models

# Create your models here.

Django/todo/items/forms.py
from django import forms
from .models import Tasks

class TaskCreateForm(forms.ModelForm):
    class Meta:
        model = Tasks
        fields = ['title', 'description']

Django/todo/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    first_name = forms.CharField(max_length=150)
    last_name = forms.CharField(max_length=150)
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['first_name','last_name','email','username','password1','password2',]

Django/todo/items/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView
from .models import Tasks
from django.views.generic import ListView, DetailView, UpdateView
from django.views.generic.edit import CreateView
from .forms import TaskCreateForm

# Create your views here.
class TaskEdit(UpdateView):
    model = Tasks
    template_name = 'items/taskedit.html'
    fields = ['title', 'description',]
    success_url = reverse_lazy('users:home')

    def form_valid(self, form):
        return super().form_valid(form)
    
    def form_invalid(self, form):
        print(form.errors)
        print('not saving')
        return super().form_invalid(form)


class CreateTask(CreateView):
    model = Tasks
    template_name = 'items/taskcreate.html'
    fields = ['title','description']
    success_url = reverse_lazy('users:home')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
   

class TaskDetail(DetailView):
    model = Tasks
    template_name = 'items/taskdetail.html'
    context_object_name = 'task'







    

Django/todo/users/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import CreateView
from .forms import SignupForm
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import logout
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import PasswordChangeView
from django.views.generic import FormView
from items.models import Tasks
from django.views.generic import ListView


# Create your views here
def index(request):
    return render(request, 'users/index.html')

class SignupView(FormView):
    form_class = SignupForm
    template_name = 'users/signup.html'
    success_url = reverse_lazy('users:index')

    def form_valid(self,form):
        user = form.save()
        return super().form_valid(form)
    
class SignInView(LoginView):
    form_class = AuthenticationForm
    template_name = 'users/signin.html'
    success_url = reverse_lazy('users:home')

class Home(ListView):
    model = Tasks
    template_name = 'users/home.html'
    context_object_name = 'tasks'

    def get_queryset(self):
        return Tasks.objects.filter(user=self.request.user)
    #return render(request, 'users/home.html')

def logoutView(request):
    logout(request)
    return redirect('users:index')

Django/todo/items/templates/items/taskcreate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Creating Task</title>
</head>
<body>
    <h1> Create Task Here ! </h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Create</button>
    </form>
   
</body>
</html>

Django/todo/items/templates/items/taskdetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasks</title>
</head>
<body>
  <h1> Task Detail ! </h1>
  <h2>{{ task.title }}</h2>
  <h3>{{ task.description }}</h3>
  <h3>{{ task.last_modified }}</h3>
  <button><a href="{% url 'items:taskedit' task.id %}">Edit Task</a></button>
  
</body>
</html>

Django/todo/items/templates/items/taskedit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Tasks</title>
</head>
<body>
    <h1> Edit Task Here ! </h1>
    <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Submit Changes</button>
</form>
</body> 
</html>

Django/todo/users/templates/users/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Signed in</title>
</head>
<body>
    <h2>Welcome {{ request.user.first_name }}. You've Successfully logged in !!</h2>
    <h2> Now you can manage your tasks ! </h2>
    <ul>
        {% for item in tasks %}
          <li><a href="{% url 'items:taskdetail' item.id %}">{{ item.title }}</a></li>
        {% endfor %}
      </ul>
      <button><a href="{% url 'items:taskcreate' %}">Create New Task</a></button>
    <button type="submit"><a href="{% url 'users:logout' %}">Logout</button></a>

</body>
</html>

Django/todo/users/templates/users/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index | Page</title>
</head>
<body>
    <h3> Home Page </h3>
    <button type="submit"><a href="{% url 'users:signin' %}">Already have an account?</a></button><br>
    <button type="submit"><a href="{% url 'users:signup' %}">Sign Up</a></button>
</body>
</html>

Django/todo/users/templates/users/signin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign | In</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        <label for="{form.username.id_for_label}">Enter Username:</label>
        {{ form.username }}
        <br><br>
        <label for="{form.password.id_for_label}">Enter your Password:</label>
        {{ form.password }}
        <br><br>
        <button type="submit">Login</button><br><br>
        <button type="submit">Forget Password</button>
    </form>
</body>
</html>

Django/todo/users/templates/users/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signup | User </title>
</head>
<body>
  <h3>Sign Up</h3>
  <form method="post">
    {% csrf_token %}
    {{ form.errors }}
    <label for="{form.first_name.id_for_label}">Enter Firstname:</label>
    {{ form.first_name}}
    <br>
    <label for="{form.last_name.id_for_label}">Enter lastname:</label>
    {{ form.last_name}}
    <br>
    <label for="{form.username.id_for_label}">Enter username:</label>
    {{ form.username}}
    <br>
    <label for="{form.email.id_for_label}">Enter Email:</label>
    {{ form.email }}
    <br>
    <label for="{form.password1.id_for_label}">Enter password:</label>
    {{ form.password1 }}
    <br>
    <label for="{form.password2.id_for_label}">Confirm password:</label>
    {{ form.password2 }}
    <br>

    <button type="submit">Sign Up</button>
  </form>
</body>
</html>