Django/A2/A2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('banks/', include('banks.urls')),
    path('accounts/', include('accounts.urls'))
]

Django/A2/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserCreate.as_view(), name='signup'),
    path('login/', views.UserLogin.as_view(), name='login'),
    path('profile/view/', views.profileView, name='view'),
    path('logout/', views.LogoutView, name='logout'),
    path('profile/',views.profile, name='profile'),
    path('profile/edit/', views.profileEdit, name='edit'),
]

Django/A2/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Bank(models.Model):
    title = models.CharField(max_length=150)
    description = models.TextField()
    last_modified = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Tasks"

    def __str__(self):
        return self.title

Django/A2/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    first_name = forms.CharField(max_length=150)
    last_name = forms.CharField(max_length=150)
    email = forms.EmailField()
    username = forms.CharField(max_length=150, error_messages={'invalid':'Incorrect Username'})

    class Meta:
        model = User
        fields = ['first_name','last_name','email','username','password1','password2',]

Django/A2/accounts/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView
from django.contrib.auth.models import User
from django.urls import reverse, reverse_lazy
from .forms import SignupForm
from django.views.generic import FormView, UpdateView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache



# Create your views here.
class UserCreate(FormView):
    form_class = SignupForm
    template_name = 'accounts/signup.html'
    success_url = reverse_lazy('accounts:login')

    def form_valid(self,form):
        user = form.save()
        return super().form_valid(form)


class UserLogin(LoginView):
    form_class = AuthenticationForm
    template_name = 'accounts/login.html'
    success_url = reverse_lazy('accounts:profile')


def LogoutView(request):
    logout(request)
    return redirect(reverse('accounts:login'))

@login_required
@never_cache
def profile(request):
    return render(request, 'accounts/home.html')


def profileView(request):
    user_info = {
        'first_name':request.user.first_name,
        'last_name':request.user.last_name,
        'email':request.user.email,
        'username':request.user.username,
    }
    return JsonResponse(user_info)

# class ProfileEdit(LoginRequiredMixin, UpdateView):
#     model = User
#     fields = ['first_name', 'last_name', 'email', 'password1', 'password2']
#     template_name = 'accounts/edit.html'
#     success_url = reverse_lazy('accounts:profile')

def profileEdit(request):
    if request.user.is_authenticated:
        first_name = request.user.first_name
        last_name = request.user.last_name
        email = request.user.email
        password1 = request.user.password
        password2 = request.user.password

    return render(request, 'accounts/edit.html',{
        'first_name':first_name,
        'last_name':last_name,
        'email':email,
        'password1':password1,
        'password2':password2
    })

    


    

Django/A2/banks/views.py
from django.shortcuts import render

# Create your views here.

Django/A2/accounts/templates/accounts/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Edit</title>
</head>
<body>
    <h1>Edit User Here !</h1>

    <form action="" method="post">
        {% csrf_token %}
        <label for="first_name">Enter First Name:</label>
        {{ first_name }}

        <button type="submit">Save Changes</button>
    </form>
</body>
</html>

Django/A2/accounts/templates/accounts/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <h1>{{ request.user.first_name }} Logged In</h1>

    

    <button type="submit"><a href="{% url 'accounts:logout' %}">Logout</a></button>
    <button type="submit"><a href="{% url 'accounts:view' %}">View</a></button>
    <button type="submit"><a href="{% url 'accounts:edit' %}">Edit User</a></button>
    <button type="submit"><a href="">Add Bank</a></button>

</body>
</html>

Django/A2/accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Form</title>
</head>
<body>
    <h1>Login Page</h1>

    <form action="" method="post">
        {% csrf_token %}

        <label for="{form.username.id_for_label}">Enter your username:</label>
        {{ form.username }}
        <br><br>
        <label for="{form.password.id_for_label}">Enter Your Password:</label>
        {{form.password }}
        <br><br>
        <button type="submit">Login</button><br><br>
        <button type="submit"><a href="{% url 'accounts:signup' %}">Don't have an account?</a></button>
        <br><br>
    </form>

    {% if form.errors %}
    <div class="error">
        <strong>There was an error with your submission:</strong>
        {{ form.errors }}
    </div>
{% endif %}

</body>
</html>

Django/A2/accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signup | Form</title>
</head>
<body>
    <form action="" method='post'>
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Create User</button><br><br>
        <button type="submit"><a href="{% url 'accounts:login' %}">Already Have an Account?</a></button>
    </form>

</body>
</html>